apiVersion: v1
kind: Service
metadata:
  annotations:
    service.cloud.tencent.com/direct-access: "true"
  labels:
    k8s-app: number-game
    qcloud-app: number-game
    service.cloud.tencent.com/loadbalance-type: OPEN
  name: number-game
spec:
  allocateLoadBalancerNodePorts: false
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8000-8000-tcp
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    k8s-app: number-game
    qcloud-app: number-game
  type: LoadBalancer
